version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: "monday"
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary

    groups:
      npm-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

    commit-message:
      prefix: "chore"
      include: "scope"
