name: Bug Report
description: File a bug report
title: '[Bug]: '
labels: ['bug', 'triage']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please [search](/beyondhb1079/s4us/issues) to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to...
        2. Click...
        3. See error...
    validations:
      required: false
  - type: dropdown
    id: devices
    attributes:
      label: What devices are you experiencing the problem on?
      description: Select all that apply.
      multiple: true
      options:
        - Desktop
        - Mobile
        - Tablet
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      description: Select all that apply.
      multiple: true
      options:
        - Chrome
        - Firefox
        - Microsoft Edge
        - Safari
        - Other
    validations:
      required: true
