name: 'Auto Dismissal of approvals on Major Changes'

on:
  pull_request:
    branches: [main]

jobs:
  dismiss-on-major-changes:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    name: Auto dismiss approval after major changes
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Skip if merge commit
        shell: bash
        run: |
          git fetch --all
          if (($(git show --no-patch --format="%P" ${{ github.event.pull_request.head.sha }} | wc -l) > 1)); then
            echo "merge_commit=true" >> $GITHUB_ENV;
          fi
      - name: Auto dismiss
        if: ${{ env.merge_commit != 'true' }}
        uses: actions/github-script@v3
        with:
          script: |
            // Get all reviews
            const reviews = await github.pulls.listReviews({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            });

            const approvals = reviews.data
              .filter(r => r.user.type == 'User')
              .filter(r => r.state == 'APPROVED')
              .sort((a, b) => a.id - b.id);

            if (approvals.length == 0) {
              // no approvals to dismiss
              return
            }

            // Obtain info about the last approval
            const lastApproval = approvals[0];
            const lastApprover = lastApproval.user.login;
            const lastApprovedCommit = lastApproval.commit_id;
            const currentCommit = context.payload.pull_request.head.sha;
            console.log("Last approval:");
            console.log(lastApproval);

            // Check for additions/removals of files
            console.log(`Checking for changes in new files in commit ${currentCommit}`);
            const { spawnSync } = require('child_process');

            let child = spawnSync('git', ['diff', '--stat' , '--diff-filter=m',  '--exit-code',lastApprovedCommit,  currentCommit]);
            let error = child.error;
            let stderr = child.stderr.toString();
            let stdout = child.stdout.toString();
            console.log('stdout: ' + stdout);
            console.log('stderr: ' + stderr);
            if (error) {
              console.log(`It looks like more than just file modifications: ${error}`);
              github.pulls.dismissReview({
                owner: context.payload.repository.owner.login,
                repo: context.payload.repository.name,
                pull_number: context.payload.pull_request.number,
                review_id: lastApproval.id,
                message: `@${context.actor}, I'm dismissing @${lastApprover}'s approval ` +
                  `as it seems you added or removed a file since their approval. ` +
                  'If you believe my dismissal was a mistake please ask about ' +
                  '[autoapprove.yaml](../../blob/main/.github/workflows/autoapprove.yaml)'
              })
              return;
            }

            // There are only modifications on existing files.
            // Make sure there aren't any more than:
            // - 5 insertions
            // - 5 deletions
            // - 10 lines changes overall

            console.log('looking for the number of modifications');
            let insertions = 0, deletions = 0;
            child = spawnSync('git', ['diff', '--histogram', '-U0', lastApprovedCommit, currentCommit]);
            error = child.error;
            stderr = child.stderr.toString();
            stdout = child.stdout.toString();
            console.log('diff since last approval: ' + stdout);
            console.log('diff since last approval stderr: ' + stderr);
            if (!error) {
              const lines = stdout.split('\n')
                .filter(l => l.startsWith('+') || l.startsWith('-'))
                .filter(l => !l.startsWith('+++') && !l.startsWith('---'));
              insertions = lines.filter(l => l.startsWith('+')).length;
              deletions = lines.filter(l => l.startsWith('-')).length;

              const maxLinesChanged = insertions + deletions;
              console.log(`Detected ${insertions} insertions and ${deletions} deletions`);

              if (maxLinesChanged <= 10 && insertions <= 5 && deletions <= 5) {
                console.log("Probably not worth another human review");
                return
              }
              console.log("Dismissing due to significant changes.");

              github.pulls.dismissReview({
                owner: context.payload.repository.owner.login,
                repo: context.payload.repository.name,
                pull_number: context.payload.pull_request.number,
                review_id: lastApproval.id,
                message: `@${context.actor}, I'm dismissing @${lastApprover}'s approval as it ` +
                  `seems you've made significant changes (+${insertions} -${deletions}) since ` + 
                  'their approval. If you believe my dismissal was a mistake please ask about ' +
                  '[autoapprove.yaml](../../blob/main/.github/workflows/autoapprove.yaml)'
              });
            } else {
              console.log('strange error: ${error}');
            }
          github-token: ${{github.token}}
