name: 'Dependabot Autoapprove - Action'

on:
  pull_request:
    branches: [main]
    paths: ['yarn.lock']

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    name: Autoapprove changes
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Autoapprove
        uses: actions/github-script@v3
        with:
          script: |
            // Skip if there are any approvals
            const reviews = await github.pulls.listReviews({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            });
            const approvals = reviews.data.filter(r => r.state == 'APPROVED');
            if (approvals.length !== 0) {
              console.log(`PR already approved by @${approvals[0].user.login}`);
              return;
            }

            // Approve and leave a comment for the human reviewer.
            github.pullRequests.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Dear human reviewer, copy and paste this to get ' +
                    'this auto merged: \n' +
                    '@dependabot squash and merge'
            })
          github-token: ${{github.token}}
